# Generated by Django 5.2 on 2025-04-27 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('budget_alert_threshold', models.IntegerField(default=80)),
                ('language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('expense_categories', models.JSONField(default=dict)),
                ('income_categories', models.JSONField(default=dict)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('savings_goal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('mobile_notifications', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
