# Generated by Django 5.2 on 2025-04-27 11:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='income_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userincome.source')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Income',
                'ordering': ['-date'],
                'permissions': [('can_view_all_income', 'Can view all user income entries'), ('can_edit_all_income', 'Can edit all user income entries'), ('can_delete_all_income', 'Can delete all user income entries'), ('can_export_income', 'Can export income data'), ('can_generate_income_reports', 'Can generate income reports')],
                'indexes': [models.Index(fields=['date'], name='userincome__date_b2688b_idx'), models.Index(fields=['owner'], name='userincome__owner_i_e4a65e_idx'), models.Index(fields=['source'], name='userincome__source__267dea_idx'), models.Index(fields=['created_at'], name='userincome__created_f5bc52_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='income_amount_positive')],
            },
        ),
    ]
